name: scpert
channels:
  - https://mirror.internal.puhui.chengfengerlai.com/repository/anaconda-pytorch/pytorch
  - https://mirror.internal.puhui.chengfengerlai.com/repository/anaconda/main
  - https://mirror.internal.puhui.chengfengerlai.com/repository/anaconda-nvidia/nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - ca-certificates=2025.2.25
  - comm=0.2.1
  - debugpy=1.6.7
  - importlib_metadata=7.0.1
  - ipykernel=6.29.5
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - pickleshare=0.7.5
  - pip=24.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wheel=0.44.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
    - absl-py==2.2.2
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - anndata==0.9.2
    - annotated-types==0.7.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==25.1.0
    - cached-property==2.0.1
    - cell-gears==0.0.2
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - chex==0.1.7
    - click==8.1.8
    - contextlib2==21.6.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - datasets==2.21.0
    - dcor==0.6
    - decorator==5.2.1
    - deprecated==1.2.18
    - dill==0.3.8
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - docrep==0.3.2
    - einops==0.8.1
    - et-xmlfile==2.0.0
    - etils==1.3.0
    - eval-type-backport==0.2.2
    - executing==2.2.0
    - filelock==3.16.1
    - flash-attn==0.2.8
    - flashmha==0.6.3
    - flax==0.7.2
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - get-annotations==0.1.2
    - gitdb==4.0.12
    - gitpython==3.1.44
    - h5py==3.11.0
    - huggingface-hub==0.30.1
    - idna==3.10
    - igraph==0.11.8
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipython==8.12.3
    - jax==0.4.13
    - jaxlib==0.4.13
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - leidenalg==0.10.2
    - lightning-utilities==0.11.9
    - llvmlite==0.41.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - ml-dtypes==0.2.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mudata==0.2.3
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - narwhals==1.42.1
    - natsort==8.4.0
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - numpyro==0.12.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.1.105
    - openpyxl==3.1.5
    - opt-einsum==3.4.0
    - optax==0.1.2
    - orbax==0.1.7
    - orbax-checkpoint==0.2.3
    - packaging==24.2
    - pandas==2.0.3
    - parso==0.8.4
    - patsy==1.0.1
    - pexpect==4.9.0
    - pillow==10.4.0
    - platformdirs==4.3.6
    - plotly==6.2.0
    - prompt-toolkit==3.0.50
    - propcache==0.2.0
    - protobuf==5.29.4
    - psutil==7.0.0
    - pure-eval==0.2.3
    - pyarrow==17.0.0
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydot==3.0.4
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.1.4
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - pytorch-lightning==1.9.5
    - pytz==2025.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==14.0.0
    - safetensors==0.5.3
    - scanpy==1.9.8
    - scgpt==0.2.4
    - scib==1.1.5
    - scikit-learn==1.3.2
    - scikit-misc==0.2.0
    - scipy==1.10.1
    - scvi-tools==0.20.3
    - seaborn==0.13.2
    - sentry-sdk==2.25.1
    - session-info==1.0.0
    - setproctitle==1.3.5
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - stdlib-list==0.10.0
    - sympy==1.13.3
    - tensorstore==0.1.45
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tokenizers==0.20.3
    - toolz==1.0.0
    - torch==2.3.0
    - torch-cluster==1.6.3+pt24cu124
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2+pt24cu124
    - torch-sparse==0.6.18+pt24cu124
    - torch-spline-conv==1.2.2+pt24cu124
    - torchmetrics==1.5.2
    - torchtext==0.18.0
    - tqdm==4.67.1
    - transformers==4.46.3
    - transforms==0.2.1
    - triton==2.3.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - umap-learn==0.5.7
    - urllib3==2.2.3
    - wandb==0.19.9
    - wcwidth==0.2.13
    - wrapt==1.17.2
    - xlrd==2.0.1
    - xxhash==3.5.0
    - yarl==1.15.2
